apiVersion: 1

datasources:
  - name: MountMidas
    type: postgres
    uid: mount_midas_pg
    url: mount-midas-db:5432
    user: mount_midas
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: mount_midas
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
